DROP TABLE IF EXISTS SYSTEM_ROLES;
DROP TABLE IF EXISTS FILE;
DROP TABLE IF EXISTS USER_SETTINGS;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS GAME_PROJECT;
DROP TABLE IF EXISTS COMPANY_DEPARTMENT;
DROP TABLE IF EXISTS PROJECT_TYPE;
DROP TABLE IF EXISTS BUSYNESS_MODEL;
DROP TABLE IF EXISTS TERRITORY;
DROP TABLE IF EXISTS EVENT_KINDS;
DROP TABLE IF EXISTS HISTORY_DETAIL;
DROP TABLE IF EXISTS HISTORY;

-- EVENT_KINDS
CREATE TABLE EVENT_KINDS
(
  EV_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор',
  NAME VARCHAR(128) NOT NULL COMMENT 'Наименование',
  COMMENT VARCHAR(512) COMMENT 'Комментарий',
  EVENT_TYPE INT NOT NULL,
  DELETED INT NOT NULL DEFAULT 0,
  PRIMARY KEY (EV_ID),
  UNIQUE (NAME, DELETED)
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT = 'Выды событий';

INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'obt', 'Open beta test', 1, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'cl', 'Коммерческий запуск', 1, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'close', 'Закрытие проекта', 1, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'MM', 'Мой мир', 1, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'OK', 'Одноклассники', 1, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'VK', 'Вконтакте', 1, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'FB', 'Face Book', 1, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'sign', 'Подписание', 2, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'pp', 'pre-production, game design document', 3, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'vs', 'vertical slice, art milestone', 3, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'abt', 'альфа-тест', 3, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'cbt', 'closed beta test', 3, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'cbt1', 'closed beta test 1 (повторный)', 3, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'cbt2', 'closed beta test 2', 3, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'анонс', 'анонс проекта', 3, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'upd-year', 'ключевое обновление проекта', 3, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'ДР', 'ДР проекта', 3, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'event', 'прочие события в проекте (конкурсы, дни рождения, развлечения игроков)', 4, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'promo', 'запущен промо-сайт, промо-акции', 4, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'upd', 'новые версии игры', 5, DEFAULT);
INSERT INTO EVENT_KINDS (EV_ID, NAME, COMMENT, EVENT_TYPE, DELETED) VALUES (DEFAULT, 'sale', 'события, мотивирующие продажи', 5, DEFAULT);

-- COMPANY_DEPARTMENT
CREATE TABLE COMPANY_DEPARTMENT
(
  CD_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор',
  NAME VARCHAR(128) NOT NULL COMMENT 'Наименование',
  COMMENT VARCHAR(512) COMMENT 'Комментарий',
  DELETED INT NOT NULL DEFAULT 0,
  PRIMARY KEY (CD_ID),
  UNIQUE (NAME, DELETED)
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT = 'Подразделение компании';

INSERT INTO COMPANY_DEPARTMENT (CD_ID, NAME, COMMENT) VALUES (DEFAULT, 'Allods studio', NULL);
INSERT INTO COMPANY_DEPARTMENT (CD_ID, NAME, COMMENT) VALUES (DEFAULT, 'DJ', NULL);
INSERT INTO COMPANY_DEPARTMENT (CD_ID, NAME, COMMENT) VALUES (DEFAULT, 'Europe', NULL);
INSERT INTO COMPANY_DEPARTMENT (CD_ID, NAME, COMMENT) VALUES (DEFAULT, 'ITT', NULL);
INSERT INTO COMPANY_DEPARTMENT (CD_ID, NAME, COMMENT) VALUES (DEFAULT, 'Mini', NULL);
INSERT INTO COMPANY_DEPARTMENT (CD_ID, NAME, COMMENT) VALUES (DEFAULT, 'Mobile', NULL);
INSERT INTO COMPANY_DEPARTMENT (CD_ID, NAME, COMMENT) VALUES (DEFAULT, 'Nord', NULL);
INSERT INTO COMPANY_DEPARTMENT (CD_ID, NAME, COMMENT) VALUES (DEFAULT, 'Operator', NULL);
INSERT INTO COMPANY_DEPARTMENT (CD_ID, NAME, COMMENT) VALUES (DEFAULT, 'Publishing', NULL);
INSERT INTO COMPANY_DEPARTMENT (CD_ID, NAME, COMMENT) VALUES (DEFAULT, 'PushKin', NULL);
INSERT INTO COMPANY_DEPARTMENT (CD_ID, NAME, COMMENT) VALUES (DEFAULT, 'Social', NULL);
INSERT INTO COMPANY_DEPARTMENT (CD_ID, NAME, COMMENT) VALUES (DEFAULT, 'TZ', NULL);

CREATE INDEX COMPANY_DEPARTMENT_INDEX ON COMPANY_DEPARTMENT (NAME(16)) USING BTREE;

-- PROJECT_TYPE
CREATE TABLE PROJECT_TYPE
(
  PT_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор',
  NAME VARCHAR(128) NOT NULL COMMENT 'Наименование',
  COMMENT VARCHAR(512) COMMENT 'Комментарий',
  DELETED INT NOT NULL DEFAULT 0,
  PRIMARY KEY (PT_ID),
  UNIQUE (NAME, DELETED)
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT = 'Тип проекта';

INSERT INTO PROJECT_TYPE (PT_ID, NAME, COMMENT) VALUES (DEFAULT, 'Client', NULL);
INSERT INTO PROJECT_TYPE (PT_ID, NAME, COMMENT) VALUES (DEFAULT, 'Mini', NULL);
INSERT INTO PROJECT_TYPE (PT_ID, NAME, COMMENT) VALUES (DEFAULT, 'Mobile', NULL);
INSERT INTO PROJECT_TYPE (PT_ID, NAME, COMMENT) VALUES (DEFAULT, 'Social', NULL);
INSERT INTO PROJECT_TYPE (PT_ID, NAME, COMMENT) VALUES (DEFAULT, 'Web', NULL);

CREATE INDEX PROJECT_TYPE_INDEX ON PROJECT_TYPE (NAME(16)) USING BTREE;

-- BUSYNESS_MODEL
CREATE TABLE BUSYNESS_MODEL
(
  BM_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор',
  NAME VARCHAR(128) NOT NULL COMMENT 'Наименование',
  COMMENT VARCHAR(512) COMMENT 'Комментарий',
  DELETED INT NOT NULL DEFAULT 0,
  PRIMARY KEY (BM_ID),
  UNIQUE (NAME, DELETED)
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT = 'Бизнес-модель';

INSERT INTO BUSYNESS_MODEL (BM_ID, NAME, COMMENT, DELETED) VALUES (DEFAULT, 'Dev', NULL, DEFAULT);
INSERT INTO BUSYNESS_MODEL (BM_ID, NAME, COMMENT, DELETED) VALUES (DEFAULT, 'In', NULL, DEFAULT);
INSERT INTO BUSYNESS_MODEL (BM_ID, NAME, COMMENT, DELETED) VALUES (DEFAULT, 'Invest', NULL, DEFAULT);
INSERT INTO BUSYNESS_MODEL (BM_ID, NAME, COMMENT, DELETED) VALUES (DEFAULT, 'Out', NULL, DEFAULT);
INSERT INTO BUSYNESS_MODEL (BM_ID, NAME, COMMENT, DELETED) VALUES (DEFAULT, 'Par', NULL, DEFAULT);

CREATE INDEX BUSYNESS_MODEL_INDEX ON BUSYNESS_MODEL (NAME(16)) USING BTREE;

-- TERRITORY
CREATE TABLE TERRITORY
(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор',
  NAME VARCHAR(128) NOT NULL UNIQUE COMMENT 'Наименование',
  PRIMARY KEY (ID)
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT = 'Территория';

INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'MENA');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'Англия');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'Бразилия');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'Весь мир');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'Германия');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'Индонезия');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'Испания');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'Италия');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'Китай');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'Корея');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'Польша');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'Россия');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'США');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'Тайвань');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'Турция');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'Филиппины');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'Франция');
INSERT INTO TERRITORY (ID, NAME) VALUES (DEFAULT, 'Япония');

-- GAME_PROJECT
CREATE TABLE GAME_PROJECT
(
  GP_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор',
  LOCAL_NAME VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Локальное наименование',
  DESCR VARCHAR(512) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT 'Описание',
  ORIG_NAME VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Оригинальное наименование',
  PR_TYPE INT UNSIGNED NOT NULL COMMENT 'Тип',
  LOGO VARCHAR(128) COMMENT 'Логотип',
  PAGE VARCHAR(128) COMMENT 'Страница',
  DEVELOPER VARCHAR(128) NOT NULL COMMENT 'Разработчик',
  COMPANY_DEPT INT UNSIGNED NOT NULL COMMENT 'Подразделение компании',
  BMODEL INT UNSIGNED NOT NULL COMMENT 'Бизнес-модель',
  STATUS INT UNSIGNED NOT NULL COMMENT 'Статус',
  TERRITORY INT UNSIGNED NOT NULL COMMENT 'Территория',
  DELETED INT NOT NULL DEFAULT 0,
  PRIMARY KEY (GP_ID),
  UNIQUE (LOCAL_NAME, DELETED),
  FOREIGN KEY (PR_TYPE) REFERENCES PROJECT_TYPE(PT_ID) ON DELETE CASCADE,
  FOREIGN KEY (BMODEL) REFERENCES BUSYNESS_MODEL(BM_ID) ON DELETE CASCADE,
  FOREIGN KEY (COMPANY_DEPT) REFERENCES COMPANY_DEPARTMENT(CD_ID) ON DELETE CASCADE,
  FOREIGN KEY (TERRITORY) REFERENCES TERRITORY(ID) ON DELETE CASCADE
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT = 'Игровой проект';

-- EVENT
CREATE TABLE EVENT
(
  EVENT_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор',
  TITLE VARCHAR(250) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Локальное наименование',
  NAME VARCHAR(250) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Локальное наименование',
  DESCR VARCHAR(512) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT 'Описание',
  GP_ID INT UNSIGNED NOT NULL,
  EK_ID INT UNSIGNED NOT NULL,
  STARTDATE DATE NOT NULL,
  STARTTIME VARCHAR(5),
  ENDDATE DATE,
  ENDTIME VARCHAR(5),
  DELETED INT NOT NULL DEFAULT 0,
  PRIMARY KEY (EVENT_ID),
  FOREIGN KEY (GP_ID) REFERENCES GAME_PROJECT(GP_ID) ON DELETE CASCADE,
  FOREIGN KEY (EK_ID) REFERENCES EVENT_KINDS(EV_ID) ON DELETE CASCADE
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT = 'Событие';

-- FILE
CREATE TABLE FILE
(
  FILE_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор',
  NAME VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Название файла',
  COMMENT VARCHAR(128) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT 'Название файла',
  CONTENT MEDIUMBLOB NOT NULL COMMENT 'Данные файла',
  EVENT_ID INT UNSIGNED COMMENT 'Идентификатор события',
  PRIMARY KEY (FILE_ID),
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID) ON DELETE CASCADE,
  INDEX FILE_INDEX (NAME(50))
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT = 'Файл';

-- SYSTEM_ROLES
CREATE TABLE SYSTEM_ROLES
(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор',
  USERNAME VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Пользователь',
  COMP_DEP_ID INT UNSIGNED COMMENT 'Подразделение компании',
  GP_ID INT UNSIGNED COMMENT 'Игровой проект',
  VP INT UNSIGNED COMMENT 'Вице-президент',
  PRIMARY KEY (ID),
  UNIQUE (USERNAME, COMP_DEP_ID),
  UNIQUE (USERNAME, GP_ID),
  INDEX SR_USER_INDEX(USERNAME)
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT = 'Роли системы';

-- HISTORY
CREATE TABLE HISTORY
(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор',
  TYPE INT  NOT NULL,
  PROJECT_ID INT UNSIGNED NOT NULL,
  UTIME TIMESTAMP NOT NULL DEFAULT NOW(),
  USER VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Пользователь',
  PRIMARY KEY (ID)
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT = 'История';

-- HISTORY_DETAIL
CREATE TABLE HISTORY_DETAIL
(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор',
  HID INT UNSIGNED NOT NULL,
  FIELD VARCHAR(500),
  OLD VARCHAR(500),
  NEW VARCHAR(500),
  PRIMARY KEY (ID),
  FOREIGN KEY (HID) REFERENCES HISTORY(ID) ON DELETE CASCADE
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT = 'Детали истории';

-- USER_SETTINGS
CREATE TABLE USER_SETTINGS
(
  USER VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Пользователь',
  PARAM VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  VALUE VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT = 'Настройки';
